# Generated by Django 3.0.6 on 2020-05-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='gerne',
            new_name='genre',
        ),
    ]
