# Generated by Django 3.0.6 on 2020-06-01 07:00

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200522_1502'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
